// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "market-info-storage/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderHistoryService is an autogenerated mock type for the OrderHistoryService type
type OrderHistoryService struct {
	mock.Mock
}

// GetHistoryOrdersByClient provides a mock function with given fields: client
func (_m *OrderHistoryService) GetHistoryOrdersByClient(client *domain.Client) ([]domain.HistoryOrder, error) {
	ret := _m.Called(client)

	var r0 []domain.HistoryOrder
	if rf, ok := ret.Get(0).(func(*domain.Client) []domain.HistoryOrder); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.HistoryOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveHistoryOrder provides a mock function with given fields: historyOrder
func (_m *OrderHistoryService) SaveHistoryOrder(historyOrder *domain.HistoryOrder) error {
	ret := _m.Called(historyOrder)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.HistoryOrder) error); ok {
		r0 = rf(historyOrder)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderHistoryService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderHistoryService creates a new instance of OrderHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderHistoryService(t mockConstructorTestingTNewOrderHistoryService) *OrderHistoryService {
	mock := &OrderHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
