services:

  clickhouse:
    container_name: market-info-storage-clickhouse
    image: yandex/clickhouse-server:latest
    restart: unless-stopped    
    ports:
      - ${CLICKHOUSE_PORT}:${CLICKHOUSE_PORT}/tcp    
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD} 
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DB_NAME}
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - ./migrations/clickhouse/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql:ro

  postgres:
    container_name: market-info-storage-postgres
    image: postgres:16    
    ports:
    - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./migrations/postgres/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql:ro

  server:
    container_name: 'market-info-storage-server'
    build:
      context: ..
    restart: unless-stopped
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    depends_on:
      - clickhouse
      - postgres
    env_file:
      - .env
    environment:
      CLICKHOUSE_HOST: clickhouse
      POSTGRES_HOST: postgres